# Generated by Django 5.1 on 2024-10-04 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_project_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicemodel',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='api.project', verbose_name='Projeto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invitation',
            name='token',
            field=models.CharField(default='rflL5A1VuOXpevBa3H6CC3mxBCakyFc5zmvmRRitJU9CXiGbbO2Q3MuRHBPDADTf', max_length=64, unique=True),
        ),
    ]
