# Generated by Django 5.1 on 2024-11-07 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_devicemodel_project_alter_invitation_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='token',
            field=models.CharField(default='YIofXWKT5ZmfmNSb8KKNXHG5We4Hdjv20ccqloofZxz5ig6BVwu3yjCQHiQFIYdB', max_length=64, unique=True),
        ),
        migrations.DeleteModel(
            name='DepartmentModel',
        ),
    ]
