# Generated by Django 5.1 on 2024-11-07 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_invitation_token_delete_departmentmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='api.project', verbose_name='Projeto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invitation',
            name='token',
            field=models.CharField(default='azslm6jlXtVlQRMUzCql9iPriGfwqLoCfhqrluMtbfXlKsKsLIHolde2MNBL0Mnp', max_length=64, unique=True),
        ),
    ]
