# Generated by Django 4.1.2 on 2024-11-10 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_category_project_alter_invitation_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="locationmodel",
            name="project",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="locations",
                to="api.project",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="devicemodel",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="devices",
                to="api.category",
                verbose_name="Categoria",
            ),
        ),
        migrations.AlterField(
            model_name="invitation",
            name="token",
            field=models.CharField(
                default="NZnv9hcTuOypIDjDnjtsKgltf7la8n6dM5kCUvoO4Xe9MUXV23Z0EwqAYNqLtulG",
                max_length=64,
                unique=True,
            ),
        ),
    ]
