# Generated by Django 5.1 on 2024-11-11 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_locationmodel_project_alter_devicemodel_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='token',
            field=models.CharField(default='gsWnaZ6WrLOPRq5dVRD5eOgKuf5kVJhFvSMld123FbP9nP8avCO3aTbXBsidwxPz', max_length=64, unique=True),
        ),
    ]
